{
  "name": "CI",
  "on": {
    "push": { "branches": ["master"] },
    "pull_request": { "branches": ["master"] },
    "workflow_dispatch": {}
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v2" },
        {
          "uses": "cachix/install-nix-action@v13",
          "with": {
            "install_url": "https://releases.nixos.org/nix/nix-2.3.9/install",
            "extra_nix_config": "experimental-features = nix-command flakes"
          }
        },
        { "name": "Build getnative", "run": "nix build .#getnative"}
      ]
    }
  }
}
